Added missing parameters for xStorageSync
dcloudio/DefinitelyTyped pull request #2
Opened 2019-05-11 17:48 UTC by sprhawk

Please fill in this template.

- [x ] Use a meaningful title for the pull request. Include the name of the package modified.
- [x ] Test the change in your own code. (Compile and run.)
- [ x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x ] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x ] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x ] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

If changing an existing definition:
- [ ] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
- [ ] Increase the version number in the header if appropriate.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

2019-05-13 10:06 UTC, zhetengbiji commented
感谢您的 pr，不过 value 类型应为 any

2019-05-13 10:07 UTC, zhetengbiji requested changes
感谢您的 pr，不过 value 类型应为 any

2019-05-13 10:07 UTC, zhetengbiji commented on types/uni-app/index.d.ts
> +    setStorageSync(key: string, value: string): any;
value: any

2019-05-13 15:55 UTC, sprhawk commented on types/uni-app/index.d.ts
> +    setStorageSync(key: string, value: string): any;
@zhetengbiji 已修改

2019-05-14 02:42 UTC, merged

2019-05-15 18:09 UTC, sprhawk commented
@zhetengbiji 你好，有另一个关于types 的问题，因为这个 repo 没有 issues，所以我提问在这里：https://ask.dcloud.net.cn/question/70715
不知道这个应该如何修复？